### ISSUE TITLE
Use DoctrineEvents to avoid seoFilling method call

### ISSUE THREAD

**Issue by devgiants** [compagnie-hyperactive/SeoBundle#2]
So far, to force Seo fields default filling, $this->get('lch.seo.tools')->seoFilling() has to be called. Use PreUpdate event to automatize this.

**Comment by mathieucap** [comment]
Push in develop. 
All `$this->get('lch.seo.tools')->seoFilling()` can be removed

**Comment by devgiants** [comment]
Last fixed with 55a5f499658fc27d93e8e5cd7badb9dd73caff73

**Comment by devgiants** [comment]
Last fixed with 55a5f499658fc27d93e8e5cd7badb9dd73caff73
